### ISSUE TITLE
Plan for repo?

### ISSUE THREAD

**Issue by henryiii** [pre-commit/action#1]
Is there a plan to add an example or a GitHub Action? (this is very intriguing)

**Comment by asottile** [comment]
yessss I'm currently waiting on support to hear back about write-back actions.  I haven't had a chance to poke at it since then -- you can see my initial attempts here: https://www.youtube.com/watch?v=5z94ANQvu1U https://github.com/asottile/test-repo-plz-ignore

**Comment by henryiii** [comment]
Glad to hear it. Will be watching. :)

For ideas, This looks interesting:  https://github.com/cirrus-actions/rebase (It runs based on a message, similar to the way the KitWare CMake bot works)

And this: https://github.com/cds-snc/github-actions/tree/master/auto-commit

**Comment by asottile** [comment]
yeah the problem is that only works for the owner of the repository and not for PRs (which is arguably where it's more important -- I'm always going to run pre-commit myself 😉 )

**Comment by henryiii** [comment]
You probably already know, but if you do write one, please make sure it shows up there: https://github.com/sdras/awesome-actions

**Comment by henryiii** [comment]
(Yes, I saw that problem in the rebase one)

**Comment by asottile** [comment]
which might mean I end up making a bot instead (assuming the permissions there are more maleable) and paying for hosting or whatever :/

**Comment by henryiii** [comment]
Now that actions is out or closer to being out of beta, has there been any progress?

**Comment by asottile** [comment]
yeah I've had some more time to play with this and think about implementation. with the cache task (I've experimented with the equivalent in azure pipelines) I think I could build a decent action

the write portion is still tricky but can be done with personal access tokens I think

still think a bot would be cleaner but I think an action is a good trade off

might hack on this [on stream](https://twitch.tv/anthonywritescode) this weekend

**Comment by asottile** [comment]
The initial release has been published! https://github.com/marketplace/actions/pre-commit
