### ISSUE TITLE
auto-fix causes status checks to hang

### ISSUE THREAD

**Issue by dudicoco** [pre-commit/action#108]
When adding the github token to the pre-commit action in order to enable auto-fixes, once the fix is push backed into the branch the required status checks hang:

![Screen Shot 2021-06-07 at 11 02 40](https://user-images.githubusercontent.com/51051860/120981231-20810600-c780-11eb-8c7b-b48f1e3da782.png)

**Comment by asottile** [comment]
sounds like a bug in github actions, nothing we can do about that

I'd recommend https://pre-commit.ci anyway, [this is deprecated](https://github.com/pre-commit/action#readme) -- and pre-commit.ci does not have that problem
