### ISSUE TITLE
terraform_docs failing on TF0.12

### ISSUE THREAD

**Issue by warrenbrown** [pre-commit/action#12]
This issue arises if the terraform module is on Terraform 12.  I tested this on a different module that is not on terraform 12 and it worked fine.  Is there a plan for this action to have an update that supports Terraform 12.

![Screen Shot 2020-02-27 at 11 41 34 AM](https://user-images.githubusercontent.com/209406/75470376-32a5af00-5956-11ea-9068-7adf6095120e.png)

**Comment by asottile** [comment]
this action doesn't have anything to do with terraform, but from the reading of the error message you probably need to install `terraform-docs` at the system (probably as a step before you invoke `pre-commit/action`)
