### ISSUE TITLE
hook has different output when run in action

### ISSUE THREAD

**Issue by musoke** [pre-commit/action#13]
I am having trouble getting a pre-commit hook to give the same output locally and when run through this action.

In particular, [isort](https://github.com/timothycrosley/isort/) seems to treat imports of the local package in tests and examples differently.
Here is an example ~~https://github.com/musoke/LearnAsYouGoEmulator/pull/1/checks?check_run_id=489363948~~ https://github.com/musoke/LearnAsYouGoEmulator/pull/2/checks?check_run_id=489372073

I am quite sure that this is not because of differences in my local isort configuration.

**Comment by asottile** [comment]
I don't see a pre-commit output in that link -- did you mean to link something else?

**Comment by musoke** [comment]
Sorry about that, this link should be correct: https://github.com/musoke/LearnAsYouGoEmulator/pull/2/checks?check_run_id=489372073

**Comment by asottile** [comment]
as for some unrelated hints:

- the version of isort you're using [here](https://github.com/musoke/LearnAsYouGoEmulator/blob/99a464fed1778cc0e484074c00cc3286886b7a72/.pre-commit-config.yaml#L18) is broken -- you want to use the not-dash-2 release
- you shouldn't need [this line](https://github.com/musoke/LearnAsYouGoEmulator/blob/99a464fed1778cc0e484074c00cc3286886b7a72/.pre-commit-config.yaml#L21)
- [this](https://github.com/musoke/LearnAsYouGoEmulator/blob/99a464fed1778cc0e484074c00cc3286886b7a72/.pre-commit-config.yaml#L130) is a mutable tag which has some reproducibility issues -- you probably want to run `pre-commit autoupdate` to get to a stable tag
- isort is very bad at identifying imports, you probably want to also use [seed-isort-config](https://github.com/asottile/seed-isort-config)

**Comment by musoke** [comment]
Thank you for those hints!  I am pretty new to pre-commit.

**Comment by asottile** [comment]
you should be able to reproduce the results locally just by running `pre-commit run --all-files` as well 🤔

**Comment by musoke** [comment]
Yes, I have been running `pre-commit run --all-files` locally, but isort doesn't make the same changes as when it runs through github actions.

**Comment by asottile** [comment]
does `env | grep -i python` or `env | grep -i virtualenv` give you anything? what about `git status` or `git clean -fxfd`?

**Comment by asottile** [comment]
fwiw, I get the same results as CI, so it's likely some (mis)configuration on your local machine

**Comment by musoke** [comment]
Ok, I'll hunt further.  

I am running anaconda, so get 
```
$ env | grep -i python
CONDA_PYTHON_EXE=/home/username/anaconda3/bin/python
```

**Comment by musoke** [comment]
Thank you for your assistance!

**Comment by asottile** [comment]
cheers!  good luck getting to the bottom of it

**Comment by musoke** [comment]
For the benefit of anyone who finds this: seems to be a known isort issue that will be fixed in next release.
https://github.com/timothycrosley/isort/issues/1147
https://github.com/timothycrosley/isort/issues/952
https://github.com/timothycrosley/isort/issues/1007
