### ISSUE TITLE
Database pool DefaultPartitionPool is full. Raise the MaxDatabaseLimit

### ISSUE THREAD

**Issue by gregnrobinson** [pre-commit/action#131]
Been getting this all morning. Figured I would post it here for visibility. Not sure what is going on. Have found some similar problems when looking around. It happens when I try and load the pre-commit action. Not sure what's going on just thought i'd share as I have not come across this type of issue before using Github Actions.

```
{"$id":"1","innerException":null,"message":"Database pool DefaultPartitionPool is full. Raise the MaxDatabaseLimit or use a different pool.","typeName":"Microsoft.TeamFoundation.Framework.Server.DatabasePoolFullException, Microsoft.TeamFoundation.Framework.Server","typeKey":"DatabasePoolFullException","errorCode":0,"eventId":3000}
```

**Comment by gregnrobinson** [comment]
Here is a recent pipeline run: https://github.com/gregnrobinson/kube-secrets/actions/runs/1569369690

**Comment by marcelsavegnago** [comment]
> Here is a recent pipeline run: https://github.com/gregnrobinson/kube-secrets/actions/runs/1569369690

I have the same problem. Apparently it's something recent.

**Comment by marcelsavegnago** [comment]
I believe it has something to do with it.
https://github.com/actions/cache/issues/698

**Comment by gregnrobinson** [comment]
Ya, I think so. It's just the one repo for me. Which I created today. So to your point, maybe something recent causing problems.

**Comment by asottile** [comment]
please report this to the upstream or use https://pre-commit.ci which will not suffer from github actions bugs
