### ISSUE TITLE
Pre-commit broken due to security changes

### ISSUE THREAD

**Issue by omer-za** [pre-commit/action#137]
Hi, I'm not sure if it's a real issue or not but i'm getting the following error since morning:
![image](https://user-images.githubusercontent.com/75115812/148925042-3ca4e81c-f5bf-426b-b41c-f3cad7c649cd.png)

I saw there's a change in GitHub security protocol that caused it to fail
https://github.blog/2021-09-01-improving-git-protocol-security-github/

I use a valid SSH key and it still fails, any idea what can be the reason?

**Comment by tomkerkhove** [comment]
I have just noticed this on the README:

> DEPRECATED this action is in maintenance-only mode and will not be accepting new features.
> 
> Please switch to using [pre-commit.ci](https://pre-commit.ci/) which is faster and has more features.

Guess it's time to move on..

**Comment by asottile** [comment]
you're using `git://` which is insecure and was disabled last year -- this isn't specific to github actions either -- github removed that protocol everywhere

fortunately the fix is easy, just use https instead

**Comment by tomkerkhove** [comment]
Is this something that is configurable?

**Comment by asottile** [comment]
thought that was clear above given "isn't specific to github actions" -- also you could always just [`git grep`](https://youtu.be/2MCtRv1ZIFQ) `git://` if you were unsure

**Comment by omer-za** [comment]
Thanks everyone, now it's all clear :)
