### ISSUE TITLE
Action fails on latest version of windows

### ISSUE THREAD

**Issue by LilSpazJoekp** [pre-commit/action#141]
I discovered that running pre-commit on `windows-latest` platform results in a run failure when the action installs its dependencies if pip 22.x is installed beforehand. More info here: https://github.com/praw-dev/praw/issues/1843 and here: https://github.com/praw-dev/praw/pull/1844

**Comment by asottile** [comment]
the failure:

> Error: The process 'C:\hostedtoolcache\windows\Python\3.10.1\x64\Scripts\pip.exe' failed with exit code 3221225477

has nothing to do with this action -- all `pip install` commands are likely to fail in that way

please report this to github actions and not us

**Comment by asottile** [comment]
note also that this is deprecated: https://github.com/pre-commit/action#readme
