### ISSUE TITLE
Please turn over project maintenance to the community

### ISSUE THREAD

**Issue by dgilman** [pre-commit/action#148]
If you lack the time to maintain this project please try and find a way to transition its maintainership to new volunteers. It is wholly unprofessional to deprecate this project to force people onto the for-profit pre-commit.ci.

To preempt some criticism: hopefully you can find someone more experienced/capable than myself to help with maintainership, but if you can't, let me throw my hat into the ring.

**Comment by asottile** [comment]
sorry but no thanks -- pre-commit.ci is free for open source and this action is unsafe 

you're absolutely free to fork this (it is permissively licensed after all) but it is deprecated and at your own support

**Comment by ljmf00** [comment]
> you're absolutely free to fork this (it is permissively licensed after all) but it is deprecated and at your own support

I made it. @dgilman feel free to contribute with suggestions https://github.com/pre-commit-fork/run-action .
