### ISSUE TITLE
Please fix "save-state" warning (by updating actions/core?)

### ISSUE THREAD

**Issue by jepler** [pre-commit/action#169]
We recently started getting a diagnostic with each use of pre-commit in an actions workflow, such as https://github.com/adafruit/circuitpython/actions/runs/3238006731

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This may require updating the actions/cache version used, or depend on the resolution of https://github.com/actions/cache/issues/953

Thank you!

**Comment by asottile** [comment]
feel free to send a patch
