### ISSUE TITLE
Caching the pre-commit envs

### ISSUE THREAD

**Issue by andyloughran** [pre-commit/action#179]
Is there potential to cache the environments that pre-commit generates within github actions, so that subsequent runs can load the environment from cache rather than have to reinitialise each run?

**Comment by andyloughran** [comment]
Apologies, it wasn't obvious, because I was modifying files.

I can see you cache it the same as the guide here: https://pre-commit.com/#github-actions-example

**Comment by asottile** [comment]
yeah that's literally what this action does
