### ISSUE TITLE
pre-commit/action@v3.0.0 Depends on actions/cache@v3 which is using Node 16 which is now deprecated

### ISSUE THREAD

**Issue by bakerkj** [pre-commit/action#189]
This is the error message:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

`actions/cache@v4` has been released for Node 20 please see https://github.com/actions/cache/releases/tag/v4.0.0
along with the specific PR https://github.com/actions/cache/pull/1284.

Thanks!

**Comment by asottile** [comment]
fwiw this is just a warning not an error.  github will transparently use the new node version without issue

**Comment by bakerkj** [comment]
@asottile yes thanks. That is definitely the case.

It does still produce a warning which does cause noise in our builds. It would be nice to fix the dependency either way.

Thanks!

**Comment by asottile** [comment]
feel free to send a patch

**Comment by bakerkj** [comment]
Thanks for the fix!
