### ISSUE TITLE
Action version updates - not duplicate

### ISSUE THREAD

**Issue by ulgens** [pre-commit/action#197]
I found multiple issues / PR about action version updates. These are got closed because they are duplicates:
* https://github.com/pre-commit/action/pull/175
* https://github.com/pre-commit/action/pull/181
* https://github.com/pre-commit/action/pull/182
* https://github.com/pre-commit/action/pull/186
* https://github.com/pre-commit/action/pull/192
* https://github.com/pre-commit/action/pull/193

This is not the newest one; I think this was the one being referred to as the original for some:
- https://github.com/pre-commit/action/pull/188

but, it got closed too. In the end, that update is still not merged. 

@asottile I can create a new PR or we can open #188 back.

**Comment by asottile** [comment]
read the room

**Comment by ulgens** [comment]
@asottile Can you please explain what you mean? The tool is not dead; thousands of projects are still using it, and the only alternative recommended by it is the commercial version itself, which doesn't solve the need if you are just looking for a simple way to run pre-commit without any additional tool or service. And the readme says it's in maintenance mode, but any attempt for maintenance gets rejected for no clear reason for a while.

I'm not coming here and yelling "WHY DON'T YOU RELESAE ANYTHING!?". There is a clear opportunity to improve, and people are willing to help with it. I think this calls for clearer conversation compared to "read the room" or "go search" (for sth that doesn't exist anymore).

**Comment by asottile** [comment]
you seem to be so upset that you missed #190 ?

**Comment by ulgens** [comment]
@asottile I don't see anything to be upset about, but I agree that this communication would have been more effective. Thanks for the link and your time.
