### ISSUE TITLE
Running this action in a specific directory?

### ISSUE THREAD

**Issue by james10424** [pre-commit/action#209]
Is there a way to run this action in a working directory other than root? My .pre-commit-config.yaml is in a sub directory and this action cannot find it.

**Comment by asottile** [comment]
what have you tried? the answer is in the README

**Comment by james10424** [comment]
I've tried:
* adding `working-directory` inside `with`
* adding `files` inside `with`
* adding `working-directory` next to `uses`

I'm sorry but where does README mention running pre-commit in another working directory?

**Comment by asottile** [comment]
are any of those things you tried options that are part of this action and are documented?

**Comment by james10424** [comment]
No because I couldn't find anything to achieve this behavior. The closest I can find is [this issue](https://github.com/pre-commit/pre-commit/issues/2317).

Please let me know how to do this or point me in the right direction if you know how.

**Comment by asottile** [comment]
there's literally only one option and if you're too lazy to even try it then I can't help you for free.  please put some effort in
