### ISSUE TITLE
Add an option to specify the version of pre-commit

### ISSUE THREAD

**Issue by azmeuk** [pre-commit/action#215]
I run a project where [some hooks are not compatible with pre-commit 4](https://github.com/PyCQA/docformatter/issues/293).
The easy way to solve the situation until the issue is fixed is to stay to pre-commit 3, but then this is not possible to use this action.

I suggest to add a parameter to specify the pre-commit version to be installed by this action.

What do you think?

**Comment by asottile** [comment]
I think you should search the issue tracker before making issues or read the first line of the readme or use PIP_CONSTRAINT

**Comment by azmeuk** [comment]
Oops. Sorry for the noise.
