### ISSUE TITLE
Weird link at pre-commit.ci

### ISSUE THREAD

**Issue by dimaqq** [pre-commit/action#216]
This repo points to pre-commit.ci as a better (?) alternative.

Which in turn has a quip that "development is streamed on twitch".

The twitch link points to a page with a single video about... cooking?

It seems to be by the same person who commits here, but it's odd anyway.

**Comment by asottile** [comment]
my vods only go up on YouTube now https://youtube.com/anthonywritescode and https://youtube.com/@anthonywritescode-vods

my streams usually have background music and despite being "copyright free" it usually gets dinged by twitch's content id thingy so I just upload the clean vod to YouTube instead 

my baking / cooking streams don't have background music so those stay up on twitch

I promise I spend 90+% writing code on stream :)
