### ISSUE TITLE
Improvement: using `uv` and `uvx`

### ISSUE THREAD

**Issue by JP-Ellis** [pre-commit/action#218]
Just floating an idea, but would you consider a PR to replace the usage of `pip` with the (comparatively faster) `uv`? Specifically, using `uv tool`?

**Comment by asottile** [comment]
please read the first line in the readme

**Comment by JP-Ellis** [comment]
Yeah, I had:

> this action is in maintenance-only mode and will not be accepting new features.

Given my suggestion isn't a new feature, I just thought I would ask. Perhaps archiving this repository is a better solution if you want to avoid noise though?

**Comment by asottile** [comment]
how is your suggestion not a new feature?

**Comment by asottile** [comment]
archiving is not right.  _maintenance_ will still happen as needed.  just no new features

**Comment by JP-Ellis** [comment]
Sorry if I annoyed you, sincerely did not mean to.

**Comment by asottile** [comment]
I didn't say you annoyed me I'm just trying to understand your logic

**Comment by JP-Ellis** [comment]
Oh, well for me, maintenance work involves keeping dependencies up to date, and also minor incremental improvements to performance/runtime. Feature work on the other hand typically involves new (typically user-facing but not always) functionality, or more significant changes to the underlying work.

Given `uv pip` is a (near) drop-in replacement to `pip` and would only provide a performance improvement, I would not have classified it as a new feature and merely maintenance.

But I understand given the simplicity of the action itself, you may consider this a new feature.

**Comment by mschoettle** [comment]
I ran into the same. A simple workaround (haven't tested it yet) should be to add a step beforehand that aliases `pip` to `uv pip`: `alias pip='uv pip'`. Otherwise, the only other solution I see is to fork this action to make it use `uv` instead.
