### ISSUE TITLE
GitLab Alternative

### ISSUE THREAD

**Issue by mattcanty** [pre-commit/action#27]
I started working with some GitLab codebases recently and was disappointed to not find a similar thing for their CI. I did look around, and if it's out there then I apologise for not finding it!

Would be interested in know where I might share this, if you think it is useful: https://gist.github.com/mattcanty/babff7e4770aa00d8ceaa312225a3b9a

It took me a little while to get right, especially the caching aspect. Note the golang image... the repo this comes from is a Go application. Therefore it is necessary for running Go pre-commit hooks. It appeared easier to use this image and install Python rather than the other way around.

Either way, I'm really happy to start using this pattern in GitLab as well.

Thanks

**Comment by asottile** [comment]
note that you're unintentionally using python2 there (and ending up with last year's pre-commit version)

**Comment by asottile** [comment]
it probably makes the most sense to add the cache information to [here](https://pre-commit.com/#managing-ci-caches)

if you'd like to contribute that, the code lives at https://github.com/pre-commit/pre-commit.github.io
