### ISSUE TITLE
Deprecated message

### ISSUE THREAD

**Issue by polothy** [pre-commit/action#32]
Got this while running this action:

```
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
```

Looks like it's a dependency in your https://github.com/pre-commit/action/blob/master/package-lock.json file?

**Comment by asottile** [comment]
can you link a job? we don't directly use octokit/rest

**Comment by polothy** [comment]
It’s a private repository. In the lock file, it looks like actions/github requires it. Looks like GitHub is deprecating their own dependencies heh. Not sure if upgrading your dependencies would help?

Either way, not a big deal, the action still works fine! Just thought I’d let you know.

Trying out pre-commit for the first time and it’s really slick, thanks!

**Comment by polothy** [comment]
Thanks! 🥇
