### ISSUE TITLE
File Not Found Error with v1.1.1

### ISSUE THREAD

**Issue by nickdibari** [pre-commit/action#35]
Hello! I came across this action for running `pre-commit` with Github actions and found it very useful. However, there seems to be a bug with the 1.1.1 version of this action. When I use this version in my workflow, I get this error:

```
File not found: '/home/runner/work/_actions/pre-commit/action/v1.1.1/dist/index.js'
```

I believe this is because the `action.yml` file is still pointing to `dist/index.js` file for the action entrypoint, when the 1.1.1 doesn't have code packaged in a `dist` directory. 

Note that v1.1.0 seems to work just fine.

**Comment by asottile** [comment]
ah shoot I tagged the wrong branch lol

**Comment by asottile** [comment]
ok should be fixed now

**Comment by nickdibari** [comment]
Happens to everyone! Thanks for the quick response :)
