### ISSUE TITLE
Provide and ability to set the git author name\email\commit message

### ISSUE THREAD

**Issue by carbohydrates** [pre-commit/action#5]
I need to have an ability to provide the commit author username, commit author email and commit message via env variables
https://github.com/pre-commit/action/blob/master/index.js#L36

**Comment by asottile** [comment]
could you explain why?

**Comment by carbohydrates** [comment]
Yes sure, thanks for asking. I want to have the ability to change the commit message because I've been asked about this. Also, I want to have an ability to change email and username because I want to change the author name in the git history and connect it to my bot account.

**Comment by asottile** [comment]
yeah I think I'm going to say no -- connecting these commits to your bot account would be wrong (your bot is not making the changes).  If there's something that's missing from the current commit message I'd be happy to take updates to it.

you're always free to fork, but I don't think this feature request is necessary or useful complexity
