### ISSUE TITLE
Add major version release?

### ISSUE THREAD

**Issue by s-weigand** [pre-commit/action#56]
Just wondering if you would be willing to add major version releases, i.e. `pre-commit/action@v2`?
If so, I have a workflow, using [`technote-space/release-github-actions`](https://github.com/technote-space/release-github-actions), to automate the process or releasing major/minor versions, on a new release.

**Comment by asottile** [comment]
I'd rather not, people can use tags just fine

**Comment by asottile** [comment]
(plus the `v2` gives the impression that it's repeatable but will surprisingly break people -- I definitely don't want to do that)

**Comment by s-weigand** [comment]
Fair enough, that's why I asked ^^
