### ISSUE TITLE
Question About Automatic PRs for Public Repositories

### ISSUE THREAD

**Issue by ssanderson** [pre-commit/action#6]
I'm working on setting up a GitHub Actions build for a public repository (see WIP at https://github.com/quantopian/pgcontents/pull/73), and I've set up a step that runs pre-commit using this action. The core functionality seems to be working great!

In the README, I noticed that, for private repositories, this action will automatically create PRs that fix auto-fixable issues when possible. That seems it'd be a great workflow, and I'd love to be able to enable it for my repository, so I'm trying to better understand why it's not currently supported for public repositories. 

My current understanding of the security model for actions, derived mostly from [this page](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token) is as follows:

For any repo with GitHub Actions enabled, GitHub automatically generates a `GITHUB_TOKEN` for each new action build, with a 60 minute expiration. That token is supplied to any actions' execution, and it grants any new pull request opened **in the repository itself** the ability to perform a variety of write operations on the repository. Any pull request opened **from a fork**, however, gets a read-only version of the token, which prevents people from being able to make modifications by opening PRs that modify the actions yaml file.

If the above is correct, then I assume you don't enable automatic PRs for public repositories because the majority of pull requests against public repos will come from forks, rather than from within the repo itself, in which case the token available to the action won't have permission to create new PRs, in either the parent repository or the originating repository. Is that correct?

**Comment by asottile** [comment]
that is indeed correct, yes

I'm working on a replacement for this which'll have the desired functionality via a bot/CI system instead of github actions, but there's a lot of work to get it off the ground (and not a huge $$$ sink)

**Comment by ssanderson** [comment]
Gotcha. That makes sense.

Thinking about what would be necessary to make this work then, it seems like any PR that's generated would need to come from a dedicated fork (or maybe from an ephemeral fork that only exists for the lifetime of the PR). 

The PR can't come from the original repo, because that would imply that the fork's author gains the ability to create PRs in the original. The PR also can't come from the forked repository, because that would imply that the original repo would have the ability to create PRs in the fork, which also seems bad (at the very least, the PR author would have to consent to this I'd think).

How does the CI/bot system you're working on handle this?

**Comment by asottile** [comment]
by default (unless you uncheck the box) a PR is editable by the repository you're contributing to

**Comment by ssanderson** [comment]
Gotcha. So is the idea then that the bot version would push commits directly to the PR?

**Comment by asottile** [comment]
yep, and with other configurable options maybe eventually (make PR against the PR (yes you can do this), etc.)

**Comment by asottile** [comment]
thanks for the question, since there's nothing else to address here I'm going to close this -- cheers!
