### ISSUE TITLE
action fails to install additional_dependencies with local hooks

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/action#75]
On https://github.com/rdo-infra/queries/runs/1721441012?check_suite_focus=true I seen an error which makes be
believe that the pre-commit version used by the action is very old / buggy, as I was not able to reproduce this locally
with current versions (2.9.3).

```
queries-schema-validation................................................Failed
- hook id: queries-schema-validation
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/work/queries/queries/src/model.py", line 4, in <module>
    from pydantic import BaseModel, Field, Extra, HttpUrl
ModuleNotFoundError: No module named 'pydantic'
```

In my case that hook was defined as:
```
  - repo: local
    hooks:
      - id: queries-schema-validation
        name: queries-schema-validation
        entry: >
          bash -c "python src/model.py && cat src/data/queries.yml | yq | jsonschema -i /dev/stdin output/queries-schema.json"
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        additional_dependencies:
          - yq
          - pydantic
          - jsonschema
```

As seend above, dependencies are included but not really installed when run using the action.

**Comment by ssbarnea** [comment]
I will use tox, as it proves more future proof, I raised this just as a reminder that using gh actions may give less controllable results.

**Comment by ssbarnea** [comment]
My mistake, apparently is not related to the action.

**Comment by asottile** [comment]
you've got `language: system` -- this has nothing to do with the action
