### ISSUE TITLE
Action versioning not following GitHub recommendations

### ISSUE THREAD

**Issue by frank-fischer-by** [pre-commit/action#79]
GitHub Actions has [_recommendations_ on how to handle releases via tagging](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management):

> * Create a release using semantic versioning. For more information, see "Creating releases."
> * Move the major version tag (such as v1, v2) to point to the Git ref of the **current** release. [...]

It would be great if this repository adapts the suggested recommendations 🙂.

That way every user could simply do

```yaml
uses: pre-commit/action@v2
```

in their GitHub action and will always get the latest 2.X.Y version.

While I saw your comments, that you do not expect big/major changes, I think many users might be/are used to referencing actions by the major version (only) for their other roles (since it's the "official" recommendation).

**Comment by asottile** [comment]
intentionally doesn't -- their recommendations are bad
