### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by elidupuis** [pre-commit/action#8]
Just tried hooking this action up on a private repository based on the README:
```
    - uses: pre-commit/action@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

and I'm getting the following error:

```
/opt/hostedtoolcache/Python/3.8.1/x64/bin/pre-commit run --all-files --show-diff-on-failure --color=always
[INFO] Initializing environment for git@github.com:pre-commit/pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
##[error]The process '/opt/hostedtoolcache/Python/3.8.1/x64/bin/pre-commit' failed with exit code 1
##[error]Node run failed with exit code 1
```

Any idea what I'm doing wrong?

**Comment by asottile** [comment]
I assume that github actions doesn't have ssh keys set up, maybe try using `https` urls instead?

**Comment by elidupuis** [comment]
Your response speed always blows me away 🙇 

Indeed, I had a `git@github.com:pre-commit/pre-commit-hooks` in my pre-commit-config file. Changing to `https://github.com/pre-commit/pre-commit-hooks` fixed the issue. Thanks!

**Comment by asottile** [comment]
:tada: awesome!

**Comment by pks10796** [comment]
Git@github.com: Permission denied (publickey). Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

**Comment by Roberto-B-23** [comment]
git@github.com: Permiso denegado (clave pública).
fatal: no se pudo leer desde el repositorio remoto.

Asegúrese de tener los derechos de acceso correctos
y el repositorio existe.      ...que tengo que hacer...?

**Comment by asottile** [comment]
perdon, no se espanol muy bien

para usar `git@github.com:...`, necesitas llave de SSH.  GitHub Actions no tiene llave de SSH.  ¿trata usar https?

___

(what I tried to say)

sorry, I don't know spanish very well

to use `git@github.com:...` you need an ssh key.  github actions does not have an ssh key. try using https?

**Comment by supercooler88** [comment]
Awesome! +1
