### ISSUE TITLE
Action in monorepos

### ISSUE THREAD

**Issue by lorinkoz** [pre-commit/action#82]
I'm trying to get this action to work in a monorepo with some local hooks. I have this config:

![image](https://user-images.githubusercontent.com/3628106/109084390-b57e5880-76d5-11eb-9501-36a6238be69f.png)

`pre-commit run -a` works locally using WSL Ubuntu 18.04.

The action fails with this error:

![image](https://user-images.githubusercontent.com/3628106/109084494-de9ee900-76d5-11eb-948a-db102edf3896.png)

Any ideas on what I could be doing wrong with the shell parameter expansion?

**Comment by asottile** [comment]
no idea because you haven't shown any reproducible or copy-pastable examples (a big hint for programming in general: never take screenshots of text, it's inaccessible, unsearchable, and generally unhelpful)

`language: system` / `bash` hooks aren't in the supported path so you're kinda on your own

**Comment by lorinkoz** [comment]
Apologies for the mistakes in filing the issue. You're totally right. Yet, your response contained the solution: I had to pass `language:  system` instead of `language: python`. Thank you!
