### ISSUE TITLE
Pre-commit hooks called twice

### ISSUE THREAD

**Issue by Nuru** [pre-commit/action#85]
When  configured with a GitHub token, the action will push back fixes to the pull request branch. However, in doing so, it runs the pre-commit hooks twice. Can we get this to run them only once?

https://github.com/pre-commit/action/blob/ec497e5c4a44eaca8283b84d85d4105e30fb6903/index.js#L55-L64

Also, can we make this a GitHub status check, so we can wait for it to finish/succeed before starting a CI build?

**Comment by asottile** [comment]
I'd recommend you read the comment you linked to, it answers your question

you absolutely can make a status check, you'll need to implement a little bit of code after the action runs based on whether it was successful or not and post to statuses -- there isn't really a good native way to do this in a github action that satisfies everyone's needs (and personally I find the "status checks" ui to be one of the worst github has created)

**Comment by Nuru** [comment]
@asottile wrote
> I'd recommend you read the comment you linked to, it answers your question

I did not link to a comment, and the comment in the code makes no sense to me. Actions run on pushes made by actions if the GITHUB_TOKEN is not the default token but is instead a token with sufficient privilege. However, even if actions never ran on pushes, I do not see any advantage to running the pre-commit twice. 

Why cannot you just use
```javascript
 const ret = await exec.exec('pre-commit', args); 
 if (!restored) { 
     await cache.saveCache(cachePaths, cacheKey); 
 } 
  
 if (ret && push) { 
    const diff = await exec.exec(
        'git', ['diff', '--quiet'], {ignoreReturnCode: true}
    );
```

> you absolutely can make a status check, you'll need to implement a little bit of code after the action runs based on whether it was successful or not and post to statuses -- there isn't really a good native way to do this in a github action that satisfies everyone's needs (and personally I find the "status checks" ui to be one of the worst github has created)

OK, you don't want to do it/it's too much work. Would you accept a PR for it?

**Comment by asottile** [comment]
>  However, even if actions never ran on pushes, I do not see any advantage to running the pre-commit twice.

if an action ran and pushed code that was broken, the action does not run again so you'd be missing a check

> OK, you don't want to do it/it's too much work. Would you accept a PR for it?

no, this isn't the right place for such a thing.  an action is a building block to making a workflow

**Comment by asottile** [comment]
feel free to fork to implement your custom behaviours if you're not happy with how this one works.  I'd also recommend your company sponsor the project if you're using this or pre-commit in private repositories for free

**Comment by asottile** [comment]
also you probably don't want to blindly push or you'll eat through all of your actions minutes on an infinite autofixing loop if you ever end up with conflicting tools
