### ISSUE TITLE
In v2.0.1 the released content does not include 'dist/index.js' file

### ISSUE THREAD

**Issue by mondeja** [pre-commit/action#90]
Compare two latest releases:

```sh
$ wget https://github.com/pre-commit/action/archive/refs/tags/v2.0.1.tar.gz
$ tar -xvzf v2.0.1.tar.gz
$ wget https://github.com/pre-commit/action/archive/refs/tags/v2.0.0.tar.gz
$ tar -xvzf v2.0.0.tar.gz
$ rm v2.0.1.tar.gz v2.0.0.tar.gz
$ ls action-2.0.0
action.yml  dist  LICENSE  README.md
$ ls action-2.0.1
action.yml  index.js  LICENSE  Makefile  package.json  package-lock.json  README.md  webpack.config.js
$ rm -r action-2.0.0 action-2.0.1
```

That causes a [file not found error running the action](https://github.com/mondeja/pytest-blender/pull/7/checks?check_run_id=2267382699#step:4:7) with latest release. It seems to me a problem with the released branch, being this **master** instead of **release**.

**Comment by s-weigand** [comment]
Just had my first coffee, going through my Monday morning routine of checking all dependabot PRs.
And when I saw the failing CI for `Bump pre-commit/action from v2.0.0 to v2.0.1` together with the release notes, I thought `Damn how did I break the pre-commit action? 😱 `.
But when investigating what went wrong I came to the same conclusion as @mondeja .

Well, it was late in the evening when @asottile made the release and the last release was over 9 months ago, so it is an understandable slip 😉 .

**Comment by maximveksler** [comment]
Faily fails for us as well on the same issue.

**Comment by asottile** [comment]
huh, looks like github tagged the wrong branch when I did it through the UI, despite using the branch dropdown to select the `release` branch

I'll do it from `git` this time

**Comment by asottile** [comment]
via v2.0.2
