### ISSUE TITLE
CI failure: The `rev` field appears to be a mutable reference

### ISSUE THREAD

**Issue by AakashGfude** [pre-commit/action#92]
I am getting the following CI error for the past couple of days, on the pre-commit Github action:

```
[WARNING] The 'rev' field of repo 'https://github.com/psf/black' appears to be a mutable reference
 (moving tag / branch).  Mutable references are never updated after first install and are not supported.  
See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  
Hint: `pre-commit autoupdate` often fixes this.
```

Has anyone else got this error lately?

**Comment by asottile** [comment]
have you tried what it told you to do?

this also isn't an error, it is just a warning unless you have somehow converted warnings to errors (?)

**Comment by nthomsencph** [comment]
It says that you are pointing to a repo reference that may change in the future. Just run `pre-commit autoupdate` as it says.
